services:
  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    command:
      - /data

    ports:
      # Accessible only from this computer
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
      RUSTFS_CONSOLE_ENABLE: "true"

      # S3 API CORS - this is what your Next.js upload needs
      RUSTFS_CORS_ALLOWED_ORIGINS: "http://localhost:3000"

      # Optional: CORS for RustFS management console
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "http://localhost:3000"

      RUSTFS_ACCESS_KEY: "${RUSTFS_ACCESS_KEY:-SYSADM}"
      RUSTFS_SECRET_KEY: "${RUSTFS_SECRET_KEY:-SYS168}"

      RUSTFS_OBS_LOGGER_LEVEL: "error"

    volumes:
      - rustfs-data:/data

    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -fsS http://127.0.0.1:9000/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  postgres:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped

    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rustfs-data:
  postgres_data:


# docker run -d --name rustfs --restart unless-stopped --env-file rustfs.env -p 127.0.0.1:9000:9000 -p 127.0.0.1:9001:9001 -v rustfs-data:/data rustfs/rustfs:latest /data