spring:
  application:
    name: file-upload-rustfs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
storage:
  rustfs:
    url: ${RUSTFS_URL:http://localhost:9000}
    region: ${RUSTFS_REGION:us-east-1}
    access-key: ${RUSTFS_ACCESS_KEY:5UApLSla1l4LWqGg9Bdn}
    secret-key: ${RUSTFS_SECRET_KEY:sLVoQ1aCuWO6gs0YNkgxQZy6pmNGv23SeBHQKYzS}
    bucket: ${RUSTFS_BUCKET:uploads}
